### PR TITLE
Financial report

### LINKED ISSUE #43: getAllEventFinanceReport
- Endpoint URI: */finance-report*
- Http Method: *GET*
- API Logic: 
    - find all events from eventRepository
    - for each event
         - get all income budget for that event, sum it up as **totalBudgetIncome**
         - get all expense budget for that event, sum it up as **totalBudgetExpenses**
         - get all income transaction for that event, sum it up as **totalIncome**
         - get all expense transaction for that event, sum it up as **totalExpenses**
- Progress
    - [x] development
    - [x] integration Test

### LINKED ISSUE #44: getFinanceReportByEventId
- Endpoint URI: */finance-report/event/{eventId}*
- Http Method: *GET*
- API Logic: 
    - find event by eventId
    - get all income budget for that event, sum it up as **totalBudgetIncome**
    - get all expense budget for that event, sum it up as **totalBudgetExpenses**
    - get all income transaction for that event, sum it up as **totalIncome**
    - get all expense transaction for that event, sum it up as **totalExpenses**
- Progress
    - [x] development
    - [x] integration Test

### LINKED ISSUE #45: getFinanceReportByYearSession
- Endpoint URI: */finance-report/year-session?yearSessionId=1*
- Http Method: *GET*
- API Logic: 
    - yearSessionId param is optional, if it is `yearSessionId == null`, 
          - will get the lastest row of yearSession in Database 
          - if no record is found in database, a `RuntimeException` will thrown (HTTP 500  status code)
    - if yearSessionId exists
          - will find `YearSession` by yearSessionId from Database 
          - get the String `value` 
          - if no record is found in database, a `BadRequestException` will thrown
    - find all transaction in that year session, based on `Transaction.createdDate`
    - create a default JSON response of 
```
{
  "INCOME": {
       "SEPTEMBER": "0.00"
       "OCTOBER": "0.00"
       ...
   },
  "EXPENSE": {
       "SEPTEMBER": "0.00"
       "OCTOBER": "0.00"
       ...
   },
}
```
- increment the amount based on transactionType and month

- Progress
    - [x] development
    - [x] integration Test

### PR DESCRIPTION
**Pull request by kachun333**
- resolve #43 
- resolve #44
- resolve #45

### CODE REVIEW

File: src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+    }
+
+    private FinanceReportDTO toFinanceReportDTO(EventDTO eventDTO) {
+        FinanceReportDTO financeReportDTO = new FinanceReportDTO();
+        financeReportDTO.setEventDTO(eventDTO);
+        return financeReportDTO;
+    }
+
+    private FinanceReportDTO mapTotalExpenses(FinanceReportDTO financeReportDTO) {
+        BigDecimal totalBudgetExpenses = transactionRepository
```
Comment (HowardYaw) [inline src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java]: naming convention is not proper i think
should be totalExpenses

File: src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+            .findAllByEventIdAndType(financeReportDTO.getEventDTO().getId(), TransactionType.EXPENSE)
+            .stream()
+            .map(Transaction::getAmount)
+            .reduce(BigDecimal.ZERO, BigDecimal::add);
+        financeReportDTO.setTotalExpenses(totalBudgetExpenses);
+        return financeReportDTO;
+    }
+
+    private FinanceReportDTO mapTotalIncome(FinanceReportDTO financeReportDTO) {
+        BigDecimal totalBudgetIncome = transactionRepository
```
Comment (HowardYaw) [inline src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java]: naming convention is not proper i think
should be totalIncome

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    private final FinanceReportService financeReportService;
+
+    private final YearSessionService yearSessionService;
+
+    public FinanceReportResource(FinanceReportService financeReportService, YearSessionService yearSessionService) {
+        this.financeReportService = financeReportService;
+        this.yearSessionService = yearSessionService;
+    }
+
+    @GetMapping("/finance-report")
```
Comment (HowardYaw) [inline src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:46]: to clarify is this a finance report of all event?  like:
{ eventId: 1, financeReport: {totalExpense: 1200, .....} }

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    }
+
+    @GetMapping("/finance-report/event/{eventId}")
+    public ResponseEntity<FinanceReportDTO> getFinanceReportByEventId(@PathVariable Long eventId) {
+        log.debug("REST request to get FinanceReport by eventId: {}", eventId);
+        Optional<FinanceReportDTO> financeReportDTO = financeReportService.findOneByEventId(eventId);
+        return ResponseUtil.wrapOrNotFound(financeReportDTO);
+    }
+
+    @GetMapping("/finance-report/year-session")
```
Comment (HowardYaw) [inline src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: if i want to have request params my API will be like:
/finance-report/year-session?yearSessionId=2019/2020
??

**Comment by HowardYaw** [comment]
Few items i need to knw what is the class doing:
[PageUtils](2dd1ad8ee942358a267d077fd1de3098cf107f7a)
[DatabaseConfiguration](f510973b55931052d4e4922ba3632da05b799683)

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java (hunk 3 above)
Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:46]: I have just added the sample JSON response in #43.  you can have a look there

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java (hunk 4 above)
Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: yes. This is currently how it works.

you have better suggestion? I prefer not to overload the `api/finance-report` endpoint tho

File: src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java (hunk 2 above)
Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java]: thanks for spotting it. fixed at 93e7723eba54fa41173ff2083b522a2ec8bac7fc

File: src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java (hunk 1 above)
Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java]: thanks for spotting it. fixed at 93e7723eba54fa41173ff2083b522a2ec8bac7fc

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java (hunk 4 above)
Comment (HowardYaw) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: My suggestion is change the url to:
api/finance-report/yearly?year-session=2019/2020
Or
api/finance-report/year-session?value=2019/2020

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java (hunk 3 above)
Comment (HowardYaw) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:46]: Look ok for now

File: src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java (hunk 4 above)
Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: sorry. my mistake. The API looks like this
`/finance-report/year-session?yearSessionId=1`
 where yearSessionId is referring to the primary key of `year_session` table.

The reason is I'm thinking the UI will have a dropdown button (where we load all dropdown options from `GET` all year_session table) then the user can switch between year_session by providing the id. I believe the f/e should not give "2019/2020" as query param because the probability of having typo is high.

if no query param is given, the last record in the  `year_session` table will be chosen. 
If no record is found in `year_session` table, a 500 error will be thrown.

Comment (HowardYaw) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: i agree user will not fill in the year session in FE
but using yearSessionId in params is good?
will it diff for use when we want to debug?
actually I dun really feel the Id column in yearSession is important. 
Initial i want to have something like the jhi_authority table

Comment (kachun333) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: we can discuss this in Friday night meeting

Comment (HowardYaw) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: ok

Comment (HowardYaw) [reply src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java:65]: Use Id as Request Param

**Review by HowardYaw — DISMISSED** [review]

**Review by LUXIANZE — APPROVED** [review]

**Review by CarlosSia — APPROVED** [review]
